{% set name = "prettymaps" %}
{% set version = "1.4" %}
{% set python_min = "3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prettymaps-{{ version }}.tar.gz
  sha256: a3c5f8d6ff1ddfd8c2ab00b5e66d876cdbc541ab8731f79f47be029fec5319df

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.20,<1.25
    - matplotlib-base >=3.9.0
    - shapely >=2.0.0
    - osmnx >=1.9.3,<2.0
    - ipykernel >=6.29.5
    - rasterio >=1.4.3
    - rioxarray >=0.18.2
    - opencv-python-headless >=4.11.0.86
    - scikit-image >=0.25.2
    - vsketch >=1.0.0
    - thefuzz >=0.22.1
    - elevation >=1.1.3
    - streamlit >=1.42.2
    - tqdm >=4.67.1
    - scikit-learn >=1.6.1

test:
  imports:
    - prettymaps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/marceloprates/prettymaps
  summary: A simple python library to draw pretty maps from OpenStreetMap data
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
