{% set name = "prettymaps" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prettymaps-{{ version }}.tar.gz
  sha256: 1f11ef4e8e86f43348ce546cd718459e8ef818163edbe0e4a6cc21a545908338

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - osmnx ==1.2.2
    - python >=3.6
    - pyyaml ==6.0.0
    - shapely >=1.8,<2.0

test:
  imports:
    - prettymaps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marceloprates/prettymaps
  summary: A simple python library to draw pretty maps from OpenStreetMap data
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
