{% set name = "prettymaps" %}
{% set version = "1.3.2" %}
{% set python_min = "3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prettymaps-{{ version }}.tar.gz
  sha256: a70ff69687beddad21e9e8f2d797635d6266a695cf48406ff349be666a1ecec1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.20,<1.25
    - matplotlib-base >=3.9.0
    - shapely >=2.0.0
    - osmnx >=1.9.3,<2.0
    - ipykernel >=6.29.5

test:
  imports:
    - prettymaps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/marceloprates/prettymaps
  summary: A simple python library to draw pretty maps from OpenStreetMap data
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
