schema_version: 1

context:
  name: prettymaps
  version: 1.4.2
  python_min: 3.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/prettymaps-${{ version }}.tar.gz
  sha256: dd1f7e58e1436f3fe61d578bda261db4ef4e1111ef8e5cc3e1be22b05c0a6b27

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    # Remove upper pin of numpy since it conflicts with vsketch/vpype
    - numpy >=1.20
    - matplotlib-base >=3.9.0
    - shapely >=2.0.0
    - osmnx >=1.9.3,<2.0
    - ipykernel >=6.29.5
    - rasterio >=1.4.3
    - rioxarray >=0.18.2
    # The headless version on Conda is erroneous as headless functionality is provided by opencv feedstock
    - opencv >=4.11.0
    - scikit-image >=0.25.2
    - vsketch >=1.0.0
    - thefuzz >=0.22.1
    - elevation >=1.1.3
    - streamlit >=1.42.2
    - tqdm >=4.67.1
    - scikit-learn >=1.6.1

tests:
  - python:
      imports:
        - prettymaps
      # disable pip checkbecause problems with numpy, opencv, and elevation versions
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  summary: A simple python library to draw pretty maps from OpenStreetMap data
  license: AGPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/marceloprates/prettymaps

extra:
  recipe-maintainers:
    - thewchan
